### ISSUE TITLE
Set up CI for project

### ISSUE THREAD

**Issue by balazsczap** [balazsczap/Habito#1]

**Comment by balazsczap** [comment]
### First version of the file .travis.yml file
The build system starts, but can't go on because of a strange license error.
[commit](https://github.com/balazsczap/Habito/blob/bd511cf3ce0a4a13f0b3c2f693433b940bbcb0e9/.travis.yml)

**Comment by balazsczap** [comment]
### Fixed the license refusal with this [commit](https://github.com/balazsczap/Habito/blob/26400a878bc761a51452150bd3fff337ad172784/.travis.yml)
Now it doesn't work because the lint tests fail.

**Comment by balazsczap** [comment]
### Disabled build failing on lint tests failure here [commit](https://github.com/balazsczap/Habito/blob/acc9b26b7b7ea5e6a79be509bc128169746b9ddc/app/build.gradle)
This should be reset later, when static code analysis is done more or less.

Now, it fails because it needs an emulator (since some of the tests are done on it).

**Comment by balazsczap** [comment]
# First [commit](https://github.com/balazsczap/Habito/blob/84b168a0a562979153349ea34fa90dcb26b83e35/.travis.yml) where the build is successful

It takes 15 to 20 minutes which is a lot  :scream:, should look into this.

**Comment by UjhelyiB** [comment]
[Pull request](https://github.com/balazsczap/Habito/pull/5) for this issue, reviewed by Ujhelyi Benedek.

**Comment by micskeiz** [comment]
OK.
