### ISSUE TITLE
Run static analysis tool, fix errors

### ISSUE THREAD

**Issue by balazsczap** [balazsczap/Habito#2]

**Comment by UjhelyiB** [comment]
Set up Codacy with the project: https://www.codacy.com/app/IET_HF/Habito/dashboard

**Comment by UjhelyiB** [comment]
Corrected the Activities:

Removed unused variables (e.g. TAG),
Documented empty methods (e.g. DetailHabitActivity.onNothingSelected() )
Added explicit scopes to variables, methods (e.g. DetailsHabitActivity.barchart )

 [commit](https://github.com/balazsczap/Habito/commit/fab3c9d24e1672569f9bd582ffb3ef9a82cc1fde)
 [commit](https://github.com/balazsczap/Habito/commit/785c14b49516fd5b3dd50f1bdc695ebc9ed10d53)
 [commit](https://github.com/balazsczap/Habito/commit/491a96236e61d27a35814b6eff3d3f9111210127)
[commit](https://github.com/balazsczap/Habito/commit/c401d5366d2742b1c441ffa1b409a9f6253f21f8)

**Comment by UjhelyiB** [comment]
Fixed the model warnings:

Introduced paramtereobject to reduce long parameter list (ReminderParameterObject, ResetParameterObjet)

[commit](https://github.com/balazsczap/Habito/commit/1a10053a473b37e3ee2c27660f6cc5df5f4606bb)

**Comment by UjhelyiB** [comment]
Removed unused elements from all classes:

unused imports (e.g. ListProvider):
[commit](https://github.com/balazsczap/Habito/commit/70e2a84112b0d38efcccdc76c247c40d2431ffb6)

unused class, methods, parameters: (e.g. removed ColorUtils class, fixed HabitBarchartViewModel)
[commit](https://github.com/balazsczap/Habito/commit/c401d5366d2742b1c441ffa1b409a9f6253f21f8)

**Comment by UjhelyiB** [comment]
Minor fixes, other cases: 

coding style: (corrected the example unit test)
[commit](https://github.com/balazsczap/Habito/commit/3dc6a3193504416f4d10feeb18875d5479403fa3)

added default case to switch (HabitList):
[commit](https://github.com/balazsczap/Habito/commit/202a140ee66cc8cfb65f9881d3cb0aaee1f74376)

**Comment by UjhelyiB** [comment]
With these, I corrected almost all the problems, Codacy mentioned (Although I corrected the one where it mentioned that methods with empty bodies should be documented, it recognises it as not solved.)

**Comment by UjhelyiB** [comment]
[Pull request](https://github.com/balazsczap/Habito/pull/7) for this issue, reviewed by Czap Balázs.

**Comment by micskeiz** [comment]
OK. Nice that the PR was really reviewed and discussed.

Be cautious with removing TAG, maybe it is not used now, but later it can be used, e.g. with log messages (http://stackoverflow.com/questions/8355632/how-do-you-usually-tag-log-entries-android).
