### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by balazsczap** [balazsczap/Habito#3]

**Comment by evavegh** [comment]
New test package created (utils), first test written for HabitoDateUtils.
Gradle dependency version modified.

[commit](https://github.com/balazsczap/Habito/commit/12fd898c971678014ad742e1a6c8eada3605bc94)

**Comment by evavegh** [comment]
## Tests for HabitoDateUtils
Another 4 tests, they all pass.
Mockito dependency added to project.

[commit1](https://github.com/balazsczap/Habito/commit/120f43725fc4e507efbee84de4e21adaffe190dd)
[commit2](https://github.com/balazsczap/Habito/commit/dbabce397797524db74596ffc0cce8d7be022f2e)

**Comment by evavegh** [comment]
## Habit unit tests
Removed final modifier from HabitRecord so now it can be mocked.
Unit tests written for Habit model class, they all pass.

[commit](https://github.com/balazsczap/Habito/commit/113f90f9211c02c748930616352060ac909aef99)

**Comment by evavegh** [comment]
[Pull request](https://github.com/balazsczap/Habito/pull/8) for the issue, reviewed by Czap Balázs.
