### ISSUE TITLE
Run code coverage for existsing tests, expand tests

### ISSUE THREAD

**Issue by balazsczap** [balazsczap/Habito#4]

**Comment by kovacstibor** [comment]
Imported project into Android Studio to make it easier to write tests and to use it's built-in code coverage tool to measure the coverage of our tests.
The **initial code coverage is 0%** as originally the project contains only a dummy irrelevant test example, so it won't be so hard to improve it!

**Comment by kovacstibor** [comment]
After this [commit](https://github.com/balazsczap/Habito/commit/12fd898c971678014ad742e1a6c8eada3605bc94) the changes in the code coverage:
4% line (3 /70) and 4% method (1/21)  coveration is added to the HabitoDateUtils class.

**Comment by evavegh** [comment]
New test package (utils) created. First test written for HabitoDateUtils.

[commit](https://github.com/balazsczap/Habito/commit/12fd898c971678014ad742e1a6c8eada3605bc94)

**Comment by evavegh** [comment]
Another 4 tests written for HabitoDateUtils. They all pass.
Mockito dependency added to project.

[commit1](https://github.com/balazsczap/Habito/commit/120f43725fc4e507efbee84de4e21adaffe190dd)
[commit2](https://github.com/balazsczap/Habito/commit/dbabce397797524db74596ffc0cce8d7be022f2e)

**Comment by kovacstibor** [comment]
After this [commit](https://github.com/balazsczap/Habito/commit/113f90f9211c02c748930616352060ac909aef99) the current code coverage is:
33% line (11/33) and 38% method (7/18) coverage in Habit class.
2% line (2/93) and 6% method (2/33) coverage in HabitRecord class.
7% line (5/70) and 14% method (3/21) coverage in HabitoDateUtils class.

1% of total lines covered.

**Comment by kovacstibor** [comment]
After this [commit](https://github.com/balazsczap/Habito/commit/a5bc1e61e127a09fb53bf0e12db4e20b30264ad0) the code coverage values:
27% line (19/70) and 23% method (5/21) coverage in HabitoDateUtils class.
33% line (1/3) and 50% method (1/2) coverage in HabitoStringUtils class (100% public API coverage).
100% coverage in ReminderParameterObject class.
100% coverage in ResetParameterObject class.

**3% of total lines covered.**

**Comment by kovacstibor** [comment]
After this [commit](https://github.com/balazsczap/Habito/commit/d467710a859a081c53bf68257f50b4a6711495a2) the current code coverage:
66% of the model classes (10/15) involved in tests, 32% of the methods (34/104) tested and 28% of the source lines (71/251).
   - 22% line (11/50) and 25% method (5/20) coverage in HabitList class.
   - 94% line (35/37) and 93% method (14/15) coverage in ResetFrequency class.

28% of the util classes (2/7) involved in tests, 13% of the methods (6/46) tested and the 11% of the source lines (20/179).

**6% of total lines covered.**

**Comment by kovacstibor** [comment]
After this [commit](https://github.com/balazsczap/Habito/commit/638eb8d29f9ba70a8c08557813ac2bb8f8a45dc6) the improvement of the code coverage:
76% of lines (20/26) and 83% of methods (10/12) covered in ReminderTime class.

Improvement:

- models package: +7% class (+1), +10% method (+10) and +8% line (+20) coverage

- **overall: +2% line coverage (=8%)**
